{
    "cli_testing.autocontinue": True,
    "cli_testing.chancy_tester": True,
    "cli_testing.ci.active": True,
    "cli_testing.ci.command": "hash dead_hosts_launcher && dead_hosts_launcher --save",
    "cli_testing.ci.end_command": "hash dead_hosts_launcher && dead_hosts_launcher --end",
    "cli_testing.ci.max_exec_minutes": 20,
    "cli_testing.cooldown_time": 0.2,
    "cli_testing.ci.commit_message": "[Autosave][Dead-Hosts::hostsVN-dead-hosts]",
    "cli_testing.ci.end_commit_message": "[Final/Result][Dead-Hosts::hostsVN-dead-hosts]",
    "cli_testing.display_mode.all": True,
    "cli_testing.display_mode.dots": True,
    "cli_testing.display_mode.execution_time": True,
    "cli_testing.display_mode.less": False,
    "cli_testing.max_workers": 5,
    "dns.server": ["8.8.8.8", "1.1.1.1"],
}
