{
    "cli_testing.autocontinue": True,
    "cli_testing.chancy_tester": True,
    "cli_testing.ci.active": True,
    "cli_testing.ci.command": "hash dead_hosts_launcher && dead_hosts_launcher --save",
    "cli_testing.ci.end_command": "hash dead_hosts_launcher && dead_hosts_launcher --end",
}
